spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/bank_auth_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      ssl:
        enabled: ${REDIS_SSL_ENABLED:false}

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}
  access-token-ttl-minutes: 15
  refresh-token-ttl-days: 7
  service-token-ttl-minutes: 2

internal:
  service-credentials:
    transaction-service:
      secret: ${TRANSACTION_SERVICE_SECRET}
    fraud-detection-service:
      secret: ${FRAUD_DETECTION_SERVICE_SECRET}