spring:
  application:
    name: api-gateway
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  cloud:
    gateway:
      server:
        webflux:
          global-cors:
            cors-configurations:
              '[/**]':
                allowedOrigins:
                  - "http://localhost:5173"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                allowedHeaders:
                  - "*"
          routes:
            - id: account-service
              uri: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/accounts/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20

            - id: transaction-service
              uri: ${TRANSACTION_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/api/v1/transactions/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20

            - id: payment-service
              uri: ${PAYMENT_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/api/v1/payments/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 20

            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10

jwt:
  public-key: ${JWT_PUBLIC_KEY}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway